---

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: set mailname
  template:
    src: hostname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0444

- name: update hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0444

- name: set nameservers and search domains
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0444

